version: '3.8'

services:
  adonis_app:
    restart: unless-stopped
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    tty: true
    volumes:
      - ./src:/app/src
    command: node build/bin/server.js
